inventory:
  path: data/raw/inventory/fandn.shp
  label_field: Flood

rasters:
  root: data/raw/rasters
  factors:
    - Elevation.tif
    - Slope.tif
    - Aspect.tif
    - Curvature.tif
    - rainfall.tif
    - TWI.tif
    - ndvi.tif
    - dtr.tif
    - spi_extract.tif
    - Geology.tif
    - lulc.tif
    - Soil.tif

patches:
  patch_size: 227
